modLoader = "javafml"
loaderVersion = "[36,)"
license = "Unlicense"

[[mods]]
modId = "rendertypecache"
version = "${version}"
displayName = "RenderTypeCache"
authors = "TeamPotato"
description = '''
A Minecraft mod.
'''
